### ISSUE TITLE
Model file is corrupted

### ISSUE THREAD

**Issue by aditya38654** [PRITHIVSAKTHIUR/Magic-Eraser-Tool#1]
The model file is corrupted. so can you please provide a link to download it

**Comment by PRITHIVSAKTHIUR** [comment]
Yeah I'll, Resolve ASAP

**Comment by PRITHIVSAKTHIUR** [comment]
I have fixed the issues and bugs. Download the content to run it locally. The 'pt' folder contains the tensor file.

https://huggingface.co/spaces/prithivMLmods/Magic-Eraser-Tool/tree/main

Supported Streamlit SDK Version

> pip install streamlit==1.34.0
